---
- name: Create Users in multiple servers
  hosts: all
  become: yes

  vars:
    users:
    - dev1
    - dev2
    - dev3

  tasks:
  - name: Craete user devop
    user:
      name: "{{ item }}"
      state: present
      shell: /bin/bash
    loop: "{{ users }}"
