---
- name: Detect failed logins
  hosts: all
  become: yes

  tasks:
  - name: Failed SSH attempts
    shell: grep "Failed password" /var/log/secure
    register: failed

  - name: Display failed attempts
    debug:
      msg:
      - "======== HOST: {{ ansible_hostname }} ========="
      - "{{ failed.stdout.lines }}"
