---
- name: Check available updates
  hosts:
  - ungrouped
  - db
  become: yes

  tasks:
  - name: Check updates
    command: dnf check-update
    register: updates
    failed_when: updates.rc not in [0, 100]
    changed_when: false

  - name: Display update list
    debug:
      msg:
      - "===== HOST: {{ inventory_hostname }} ====="
      - "{{ updates.stdout_lines }}"
