---
- name: Create compressed backups
  hosts: servers
  become: yes

  tasks:
  - name: Create backup archive
    archive:
      path: /etc
      dest: "/tmp/{{ inventory_hostname }}_backup.tar.gz"
      format: gz
      remove: no
